[platformio]
default_envs = esp32-s3-zero

[env:esp32-s3-zero]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.partitions = partitions_4MB.csv
board_upload.flash_size = 4MB

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4

monitor_speed = 115200
upload_speed = 921600
upload_port = COM3
monitor_port = COM3
